name: galleria
services:
  app:
    container_name: nextjs-galleria
    image: galleria
    build:
      context: ./
      target: runner
      args:
        entity: galleria
      tags:
        - galleria
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /photos:/photos
      - ./.docker/:/app/.docker/
    network_mode: bridge
    ports:
      - "127.0.0.1:3000:3000/tcp"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: unixgram:///run/systemd/journal/dev-log
        tag: "{{.Name}}/{{.ID}}"
